### ISSUE TITLE
Error when running docker-compose up

### ISSUE THREAD

**Issue by jonleopard** [mike-hearn/base16-vim-lightline#1]
Hello!

So I forked this project and ran it successfully a few months ago (I wanted to pull in the latest themes I was building). I tried running it again today and I think there are some new templates that are causing an issue when building. I get the following error when running `docker-compose up`. 

```
time="2019-02-27T11:02:47Z" level=fatal msg="open templates/telegram-desktop/themes/base16-mexico-light: is a directory"
ERROR: Service 'builder' failed to build: The command '/bin/sh -c ./base16-builder-go build' returned a non-zero code: 1
```

This is probably an error upstream (from base16-builder-go), but I thought I would ask your thoughts first. My experience with go/docker is fairly limited, so forgive me if the issue is obvious.

Thanks for making this!

**Comment by jonleopard** [comment]
The issue is being caused by a new template added upstream (the telegram-desktop ones). The maintainer of [base16-builder-go](https://github.com/belak/base16-builder-go) has [added](https://github.com/belak/base16-builder-go/issues/10#issuecomment-471044039) the `--ignore-errors`  flag as a temporary fix until this gets resolved. 

Closing this now, but feel free to follow along over there if you are curious.

**Comment by belak** [comment]
Note that it would probably be smart to specify `vim-lightline` in the build command so this repo only builds the relevant templates. This should fix the error and make builds faster

**Comment by mike-hearn** [comment]
Thank you both for flagging this. I just re-ran the Docker file and it looks like this particular error isn't an issue anymore, and it was able to produce all the vim lightline colorschemes. I've updated master with the new themes in https://github.com/mike-hearn/base16-vim-lightline/commit/cea11b7d0a407eccf0085feefb5e3be2ec99bdbb.

**Comment by belak** [comment]
Yes, because we disabled telegram upstream. It would still make sense to specify vim-lightline in the command line because the build will be much faster without generating unnecessary templates
