### ISSUE TITLE
Missing base16-default-dark

### ISSUE THREAD

**Issue by jrock2004** [mike-hearn/base16-vim-lightline#2]
Getting error that base16-default-dark could not be found. I have installed your addon. Is that naming not correct?

**Comment by mike-hearn** [comment]
https://github.com/mike-hearn/base16-vim-lightline/blob/master/autoload/lightline/colorscheme/base16_default_dark.vim

Try using underscores:

```vim
let g:lightline = {}
let g:lightline.colorscheme = "base16_default_dark"
```

**Comment by jrock2004** [comment]
Underscores did the trick. Thanks
